In [47]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.callbacks import ModelCheckpoint,EarlyStopping

import matplotlib.pyplot as plt
import numpy as np
import os
import tensorflow as tf
from keras.utils import to_categorical
from keras.preprocessing.image import array_to_img, img_to_array, load_img
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import optimizers, initializers, regularizers, metrics
import cv2
from glob import glob


In [53]:
# import Augmentor

# # 증강 시킬 이미지 폴더 경로
# img = Augmentor.Pipeline("C:/Users/82106/Desktop/cnn2/test")

# # 좌우 반전
# img.flip_left_right(probability=1.0) 


# # 증강 이미지 수
# img.sample(1000)

In [54]:
train_images = glob('C:\\Users\\82106\\Desktop\\cnn2\\train\\*')
test_images = glob('C:\\Users\\82106\\Desktop\\cnn2\\test\\*')
dic = {'normal':0, 'ad':1}
print(len(train_images))
print(len(test_images))
# print(train_images)

160
120


In [55]:
X_train = list()
Y_train = list()

for imagename in train_images:
    image = cv2.imread(imagename)
    image = cv2.resize(image, dsize=(28, 28))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    image = np.array(image)
    X_train.append(image)
    label = imagename.split('\\')
    label = label[6]
    label = label.split('_')
    label = str(label[0])
    label = dic[label]
    Y_train.append(label)

X_train = np.array(X_train)
Y_train = np.array(Y_train)
print(X_train)
print(Y_train)
print('X_train shape: ', X_train.shape)
print('Y_train shape: ', Y_train.shape)

[[[ 0  0  9 ...  9  0  0]
  [ 0  0  9 ...  9  0  0]
  [ 0  0  9 ...  9  0  0]
  ...
  [ 0  0  9 ...  9  0  0]
  [ 0  0  9 ...  9  0  0]
  [ 0  0  9 ...  9  0  0]]

 [[ 0  0  5 ...  5  0  0]
  [ 0  0  5 ...  5  0  0]
  [ 0  0  5 ...  5  0  0]
  ...
  [ 0  0  5 ...  5  0  0]
  [ 0  0  5 ...  5  0  0]
  [ 0  0  5 ...  5  0  0]]

 [[ 0  0 11 ... 11  0  0]
  [ 0  0 11 ... 11  0  0]
  [ 0  0 11 ... 11  0  0]
  ...
  [ 0  0 11 ... 11  0  0]
  [ 0  0 11 ... 11  0  0]
  [ 0  0 11 ... 11  0  0]]

 ...

 [[ 0  0 12 ... 10  0  0]
  [ 0  0 12 ... 11  0  0]
  [ 0  0 15 ... 12  0  0]
  ...
  [ 0  0 11 ... 10  0  0]
  [ 0  0 12 ... 14  0  0]
  [ 0  0 12 ... 16  0  0]]

 [[ 0  0 15 ... 16  0  0]
  [ 0  0 15 ... 16  0  0]
  [ 0  0 16 ... 16  0  0]
  ...
  [ 0  0 15 ... 16  0  0]
  [ 0  0 15 ... 16  0  0]
  [ 0  0 15 ... 16  0  0]]

 [[ 0  0 10 ... 10  0  0]
  [ 0  0  9 ...  9  0  0]
  [ 0  0  8 ...  9  0  0]
  ...
  [ 0  0  9 ... 10  0  0]
  [ 0  0  9 ... 10  0  0]
  [ 0  0  9 ... 12  0  0]]]
[1 1 1 1 1

In [56]:
X_test = list()
Y_test = list()

for imagename in test_images:
    image = cv2.imread(imagename)
    image = cv2.resize(image, dsize=(28, 28))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    image = np.array(image)
    X_test.append(image)
    label = imagename.split('\\')
    label = label[6]
    label = label.split('_')
    label = str(label[0])
    label = dic[label]
    Y_test.append(label)

X_test = np.array(X_test)
Y_test = np.array(Y_test)
print(X_test)
print(Y_test)
print('X_test shape: ', X_test.shape)
print('Y_test shape: ', Y_test.shape)

[[[ 0  0 18 ... 18  0  0]
  [ 0  0 18 ... 18  0  0]
  [ 0  0 19 ... 18  0  0]
  ...
  [ 0  0 18 ... 18  0  0]
  [ 0  0 18 ... 18  0  0]
  [ 0  0 18 ... 18  0  0]]

 [[ 0  0 15 ... 14  0  0]
  [ 0  0 13 ... 14  0  0]
  [ 0  0 15 ... 13  0  0]
  ...
  [ 0  0 14 ... 13  0  0]
  [ 0  0 13 ... 11  0  0]
  [ 0  0 11 ... 11  0  0]]

 [[ 0  0 13 ... 13  0  0]
  [ 0  0 13 ... 13  0  0]
  [ 0  0 13 ... 13  0  0]
  ...
  [ 0  0 13 ... 13  0  0]
  [ 0  0 13 ... 13  0  0]
  [ 0  0 13 ... 13  0  0]]

 ...

 [[ 0  0 24 ... 24  0  0]
  [ 0  0 24 ... 24  0  0]
  [ 0  0 24 ... 24  0  0]
  ...
  [ 0  0 25 ... 26  0  0]
  [ 0  0 24 ... 25  0  0]
  [ 0  0 25 ... 24  0  0]]

 [[ 0  0 15 ... 15  0  0]
  [ 0  0 15 ... 15  0  0]
  [ 0  0 15 ... 15  0  0]
  ...
  [ 0  0 15 ... 15  0  0]
  [ 0  0 15 ... 15  0  0]
  [ 0  0 15 ... 15  0  0]]

 [[ 0  0 11 ... 11  0  0]
  [ 0  0 11 ... 11  0  0]
  [ 0  0 11 ... 11  0  0]
  ...
  [ 0  0 11 ... 11  0  0]
  [ 0  0 11 ... 11  0  0]
  [ 0  0 11 ... 11  0  0]]]
[1 1 1 1 1

In [57]:
img_rows = 28
img_cols = 28
X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)

X_train = X_train.astype('float') / 255
X_test = X_test.astype('float')/ 255
print(X_train.shape)
print(X_test.shape)

(160, 28, 28, 1)
(120, 28, 28, 1)


In [58]:
Y_train = to_categorical(Y_train, 2)
Y_test = to_categorical(Y_test, 2)
print(Y_train.shape)
print(Y_test.shape)

(160, 2)
(120, 2)


In [59]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), input_shape=(28, 28, 1), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128,  activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

MODEL_DIR = './model/'
if not os.path.exists(MODEL_DIR):
    os.mkdir(MODEL_DIR)
    
modelpath="./model/{epoch:02d}-{val_loss:.4f}.hdf5"
checkpointer = ModelCheckpoint(filepath=modelpath, monitor='val_loss', verbose=1, save_best_only=True)
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10)

In [60]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dropout_4 (Dropout)          (None, 128)              

In [61]:
history = model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=50, batch_size=300, verbose=1, callbacks=[early_stopping_callback,checkpointer])


Epoch 00001: val_loss improved from inf to 0.68063, saving model to ./model/01-0.6806.hdf5

Epoch 00002: val_loss improved from 0.68063 to 0.66849, saving model to ./model/02-0.6685.hdf5

Epoch 00003: val_loss improved from 0.66849 to 0.64318, saving model to ./model/03-0.6432.hdf5

Epoch 00004: val_loss improved from 0.64318 to 0.61559, saving model to ./model/04-0.6156.hdf5

Epoch 00005: val_loss improved from 0.61559 to 0.59186, saving model to ./model/05-0.5919.hdf5

Epoch 00006: val_loss improved from 0.59186 to 0.56832, saving model to ./model/06-0.5683.hdf5

Epoch 00007: val_loss improved from 0.56832 to 0.54713, saving model to ./model/07-0.5471.hdf5

Epoch 00008: val_loss improved from 0.54713 to 0.51685, saving model to ./model/08-0.5168.hdf5

Epoch 00009: val_loss improved from 0.51685 to 0.48844, saving model to ./model/09-0.4884.hdf5

Epoch 00010: val_loss improved from 0.48844 to 0.47212, saving model to ./model/10-0.4721.hdf5

Epoch 00011: val_loss improved from 0.47212

In [62]:
score = model.evaluate(X_test, Y_test)
print("Test Score: %.4f" % score[0])
print("Test Accuracy: %.4f" % score[1])

120/120 [==============================] - 0s 410us/step
Test Score: 0.0670
Test Accuracy: 0.9667
